services:
#   develop:
#     container_name: "full-todos-api"
#     image: "full-todos-api"
#     build: .
#     ports:
#       - "2026:8000"
#     environment:
#       - DATABASE_URL=postgresql://todos_user:todos_pass@db:5432/todos_db
#     depends_on:
#       db:
#         condition: service_healthy
#     develop:
#       watch:
#         - action: sync
#           path: .
#           target: /app
#           ignore:
#             - .venv/
#         - action: rebuild
#           path: ./pyproject.toml
  db:
    container_name: "full-todos-db"
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=todos_db
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d todos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
