services:
#   develop:
#     container_name: "full-todos-api"
#     image: "full-todos-api"
#     build: .
#     ports:
#       - "2026:8000"
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#     depends_on:
#       db:
#         condition: service_healthy
#     develop:
#       watch:
#         - action: sync
#           path: .
#           target: /app
#           ignore:
#             - .venv/
#         - action: rebuild
#           path: ./pyproject.toml
  db:
    container_name: "full-todos-db"
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
